### ISSUE TITLE
invalid read syntax

### ISSUE THREAD

**Issue by DamienCassou** [phillord/assess#10]
When I press `C-u C-M-x` (`edebug-eval-defun`) inside test below, I get this error message:

> edebug-syntax-error: Invalid read syntax: "Failed matching", (&rest &or (symbolp &optional form) symbolp)

The test is:

```emacs
(ert-deftest add-dependency-should-add-a-file ()
  (assess-with-temp-buffers
      ((a (insert "hello")
          (insert "goodbye"))
       (b (insert "goodbye")))
    (assess= a b)))
```

**Comment by DamienCassou** [comment]
I think the `debug` declaration of `assess-with-temp-buffers` is broken. It reuses the one of `let`, but `let` doesn't allow expressions to be listed like that.

A workaround is to wrap the expressions in a `progn` like this:

``` emacs
(ert-deftest add-dependency-should-add-a-file ()
  (assess-with-temp-buffers
      ((a (progn
              (insert "hello")
              (insert "goodbye")))
       (b (insert "goodbye")))
    (assess= a b)))
```

That works because this is what someone would do with `let`.

**Comment by phillord** [comment]
Good catch!

edebug forms are painful. I think this commit addresses. Can you confirm?

**Comment by DamienCassou** [comment]
That's much better, thank you.

**Comment by phillord** [comment]
Thanks for the report!
