### ISSUE TITLE
Comparison of buffer content without properties

### ISSUE THREAD

**Issue by DamienCassou** [phillord/assess#11]
Regularly, I want to compare a buffer's content with a particular string. `assess=` seems to be what I want, but it won't work if syntax highlighting is activated because of text properties. When I don't care about text properties, would it be possible to pass an additional parameter to `assess=` so that it ignores text properties (e.g., using `buffer-substring-no-properties`)?

**Comment by phillord** [comment]
This sounds like a good idea, so I tried writing some test cases.

    (ert-deftest strings-with-unequal-propertyies ()
      (should-not
       (assess=
        (propertize "hello" 'property 1)
        "hello"))
      (should-not
       (assess-with-temp-buffers
           ((a (insert ";; Commented")
               (emacs-lisp-mode)
               (font-lock-ensure))
            (b (insert ";; Commented")
               (font-lock-ensure)))
         (assess= a b))))

But these fail for the status quo. And, checking, ultimately, `assess=`
grounds out in a call to `string=` which already ignores properties.

Which leaves me with two questions. Why isn't it working for you? And, do
I need something to force comparison of text properties?

(Oh, apologies for slow response for the third time tonight!)

**Comment by DamienCassou** [comment]
I will close the issue for now and reopen if I manage to reproduce it. Thanks for looking into it. If you want to advertise that `assess=` ignores properties, you might want to add the opposite of this test to your current test suite :-). Thanks.

**Comment by phillord** [comment]
It's a good call and I've added!
