### ISSUE TITLE
Moving to core emacs?

### ISSUE THREAD

**Issue by gonewest818** [phillord/assess#16]
Is moving to core Emacs still [on the roadmap](https://github.com/phillord/assess#roadmap)? Any prediction which Emacs release it will be?

**Comment by phillord** [comment]
It's in the roadmap in the sense that I think it's a good idea, but I
haven't found the time to do this.

As Emacs-26 is in pre-test, it would be Emacs-27 soonest.

Phil

**Comment by gonewest818** [comment]
got it, thanks!
