### ISSUE TITLE
tests fail with GNU Emacs 26.1

### ISSUE THREAD

**Issue by dogsleg** [phillord/assess#17]
Hi,

two tests, explanation-extraction-from-result and plist-extraction, fail with GNU Emacs 26.1. These tests ran successfully with the previous GNU Emacs version (at least, with 25.2). Please, find the test log attached.

$ emacs --version
GNU Emacs 26.1
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

$ emacs --batch -q --directory=. --load assess-discover.el --funcall assess-discover-run-and-exit-batch
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/20apel.el (source)...
Loading /etc/emacs/site-start.d/50asymptote.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50boxes.el (source)...
Loading /etc/emacs/site-start.d/50coq.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50figlet.el (source)...
Loading /etc/emacs/site-start.d/50gettext.el (source)...
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...
Loading /usr/share/emacs/site-lisp/latex-cjk-common/cjk-enc.el (source)...
Loading /etc/emacs/site-start.d/50latex-cjk-thai.el (source)...
Loading /etc/emacs/site-start.d/50pymacs.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Loading /etc/emacs/site-start.d/50texlive-lang-english.el (source)...
Loading /home/dogsleg/freedom/packaging/elpa/assess/test/assess-call-test.el (source)...
Loading /home/dogsleg/freedom/packaging/elpa/assess/test/assess-discover-test.el (source)...
Loading /home/dogsleg/freedom/packaging/elpa/assess/test/assess-robot-test.el (source)...
Loading /home/dogsleg/freedom/packaging/elpa/assess/test/assess-test.el (source)...
Running 45 tests (2019-01-01 15:19:19+0500)
Indenting region...
Indenting region...done
   passed   1/45  assess--test-indent-in-mode
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed   2/45  assess--test-indentation=
   passed   3/45  assess-call-return-value
   passed   4/45  assess-call-test-capture-fail
   passed   5/45  assess-call-test-hook-fail
   passed   6/45  assess-call-test-hook-test
   passed   7/45  assess-discover-test
   passed   8/45  assess-discover-test-has-this-been-defined
   passed   9/45  assess-robot-test-execute-kmacro
   passed  10/45  assess-robot-test-with-switched-buffer
   passed  11/45  assess-robot-test-with-switched-buffer-string
   passed  12/45  assess-robot-test-with-temp-switched-buffer
   passed  13/45  assess-test-create-multiple-directories-and-files
   passed  14/45  assess-test-create-multiple-files
   passed  15/45  assess-test-create-nested-directories
   passed  16/45  assess-test-create-non-empty-file
   passed  17/45  assess-test-create-non-empty-nested-file
   passed  18/45  assess-test-face-at-multiple-faces
   passed  19/45  assess-test-face-at-multiple-positions
   passed  20/45  assess-test-face-at-simple
   passed  21/45  assess-test-face-at-with-m-buffer
   passed  22/45  assess-test-face-at-with-strings
   passed  23/45  assess-test-file-face-at
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed  24/45  assess-test-file-roundtrip-indentation-explain=
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed  25/45  assess-test-file-roundtrip-indentation=
   passed  26/45  assess-test-nest-files-recursively
   passed  27/45  assess-test-related-file
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed  28/45  assess-test-roundtrip-indentation-explain=
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed  29/45  assess-test-roundtrip-indentation=
   passed  30/45  assess-test-with-find-file
   passed  31/45  buffer-string=
   passed  32/45  buffer=
   passed  33/45  call-capture
   passed  34/45  call-capture-deep
   passed  35/45  call-capture-twice
   passed  36/45  explanation-extraction
Test explanation-extraction-from-result backtrace:
  signal(ert-test-failed (((should (assess-test--explanation-from-resu
  ert-fail(((should (assess-test--explanation-from-result (ert-run-tes
  (if (unwind-protect (setq value-107 (apply fn-105 args-106)) (setq f
  (let (form-description-109) (if (unwind-protect (setq value-107 (app
  (let ((value-107 'ert-form-evaluation-aborted-108)) (let (form-descr
  (let* ((fn-105 (function assess-test--explanation-from-result)) (arg
  (closure (t) nil (let* ((fn-105 (function assess-test--explanation-f
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name explanation-extraction-from-result :d
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit(nil)
  assess-discover-run-and-exit-batch()
  command-line-1(("--directory=." "--load" "assess-discover.el" "--fun
  command-line()
  normal-top-level()
Test explanation-extraction-from-result condition:
    (ert-test-failed
     ((should
       (assess-test--explanation-from-result
	(ert-run-test ...)))
      :form
      (assess-test--explanation-from-result #s(ert-test-failed ""
							       (...)
							       (...)
							       (... ... ... ... ... ... ... ... ... ... ...)
							       nil))
      :value nil))
   FAILED  37/45  explanation-extraction-from-result
   passed  38/45  file-string=
Can’t guess python-indent-offset, using defaults: 4
Can’t guess python-indent-offset, using defaults: 4
   passed  39/45  issue-4-has-type-face
Indenting region...
Indenting region...done
Indenting region...
Indenting region...done
   passed  40/45  issue-5-test-example
Test plist-extraction backtrace:
  signal(ert-test-failed (((should (equal (assess-test--plist-from-res
  ert-fail(((should (equal (assess-test--plist-from-result (ert-run-te
  (if (unwind-protect (setq value-97 (apply fn-95 args-96)) (setq form
  (let (form-description-99) (if (unwind-protect (setq value-97 (apply
  (let ((value-97 'ert-form-evaluation-aborted-98)) (let (form-descrip
  (let* ((fn-95 (function equal)) (args-96 (condition-case err (let ((
  (closure (t) nil (let* ((fn-95 (function equal)) (args-96 (condition
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name plist-extraction :documentation nil :
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit(nil)
  assess-discover-run-and-exit-batch()
  command-line-1(("--directory=." "--load" "assess-discover.el" "--fun
  command-line()
  normal-top-level()
Test plist-extraction condition:
    (ert-test-failed
     ((should
       (equal
	(assess-test--plist-from-result ...)
	'...))
      :form
      (equal nil
	     (:form
	       (eq 1 2)
	       :value nil))
      :value nil :explanation
      (different-types nil
		       (:form
			 (eq 1 2)
			 :value nil))))
   FAILED  41/45  plist-extraction
   passed  42/45  preserved-buffer-list
   passed  43/45  strings-with-unequal-properties
   passed  44/45  to-string
   passed  45/45  with-temp-buffers

Ran 45 tests, 43 results as expected, 2 unexpected (2019-01-01 15:19:27+0500)

2 unexpected results:
   FAILED  explanation-extraction-from-result
   FAILED  plist-extraction

**Comment by phillord** [comment]
Strange, I am not seeing this. Is this a release Emacs or self-compiled? On what OS?

**Comment by dogsleg** [comment]
It is GNU Emacs from the official repository of Debian's unstable release (and recently testing too, which will become the next stable release). The exact version of the package is 1:26.1+1-3. I'm running emacs-lucid, but tests fail both with emacs-lucid and emacs-nox. You can find more information on the package at [Debian Package Tracker](https://tracker.debian.org/pkg/emacs).

**Comment by dogsleg** [comment]
I've tried to run tests with the last commits and they ran successfully:

$ emacs --batch -q   --directory=.   --load assess-discover.el       --eval '(assess-discover-run-and-exit-batch t)'
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/20apel.el (source)...
Loading /etc/emacs/site-start.d/50asymptote.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50boxes.el (source)...
Loading /etc/emacs/site-start.d/50coq.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50figlet.el (source)...
Loading /etc/emacs/site-start.d/50gettext.el (source)...
Loading /etc/emacs/site-start.d/50latex-cjk-common.el (source)...
Loading /usr/share/emacs/site-lisp/latex-cjk-common/cjk-enc.el (source)...
Loading /etc/emacs/site-start.d/50latex-cjk-thai.el (source)...
Loading /etc/emacs/site-start.d/50pymacs.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Loading /etc/emacs/site-start.d/50texlive-lang-english.el (source)...
Loading /home/dogsleg/tmp/assess/test/assess-call-test.el (source)...
Loading /home/dogsleg/tmp/assess/test/assess-discover-test.el (source)...
Loading /home/dogsleg/tmp/assess/test/assess-robot-test.el (source)...
Loading /home/dogsleg/tmp/assess/test/assess-test.el (source)...
Running 45 tests (2019-01-03 11:07:18+0500)
   passed   1/45  assess--test-indent-in-mode
   passed   2/45  assess--test-indentation=
   passed   3/45  assess-call-return-value
   passed   4/45  assess-call-test-capture-fail
   passed   5/45  assess-call-test-hook-fail
   passed   6/45  assess-call-test-hook-test
   passed   7/45  assess-discover-test
   passed   8/45  assess-discover-test-has-this-been-defined
   passed   9/45  assess-robot-test-execute-kmacro
   passed  10/45  assess-robot-test-with-switched-buffer
   passed  11/45  assess-robot-test-with-switched-buffer-string
   passed  12/45  assess-robot-test-with-temp-switched-buffer
   passed  13/45  assess-test-create-multiple-directories-and-files
   passed  14/45  assess-test-create-multiple-files
   passed  15/45  assess-test-create-nested-directories
   passed  16/45  assess-test-create-non-empty-file
   passed  17/45  assess-test-create-non-empty-nested-file
   passed  18/45  assess-test-face-at-multiple-faces
   passed  19/45  assess-test-face-at-multiple-positions
   passed  20/45  assess-test-face-at-simple
   passed  21/45  assess-test-face-at-with-m-buffer
   passed  22/45  assess-test-face-at-with-strings
   passed  23/45  assess-test-file-face-at
   passed  24/45  assess-test-file-roundtrip-indentation-explain=
   passed  25/45  assess-test-file-roundtrip-indentation=
   passed  26/45  assess-test-nest-files-recursively
   passed  27/45  assess-test-related-file
   passed  28/45  assess-test-roundtrip-indentation-explain=
   passed  29/45  assess-test-roundtrip-indentation=
   passed  30/45  assess-test-with-find-file
   passed  31/45  buffer-string=
   passed  32/45  buffer=
   passed  33/45  call-capture
   passed  34/45  call-capture-deep
   passed  35/45  call-capture-twice
   passed  36/45  ensure-string
   passed  37/45  explanation-extraction
   passed  38/45  explanation-extraction-from-result
   passed  39/45  file-string=
   passed  40/45  issue-4-has-type-face
   passed  41/45  issue-5-test-example
   passed  42/45  plist-extraction
   passed  43/45  preserved-buffer-list
   passed  44/45  strings-with-unequal-properties
   passed  45/45  with-temp-buffers

Ran 45 tests, 45 results as expected (2019-01-03 11:07:18+0500)

So, I'm closing the issue. Could you be so kind to prepare the current repository state as a new release, please?

**Comment by phillord** [comment]
Good stuff. I will make a new release.
