### ISSUE TITLE
tests fail with GNU Emacs 29.1

### ISSUE THREAD

**Issue by dogsleg** [phillord/assess#19]
Hi,

Thanks for your work on assess.

I'm getting the following error message when running tests against GNU Emacs 29.1 from the Debian unstable archive (the package version is 29.1+1-5):

```
$ emacs -batch -Q -l package --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa\")" --eval "(add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\")" -f package-initialize -L . -L test -l test/assess-call-test.el -l test/assess-test.el -l test/assess-robot-test.el -l test/assess-discover-test.el --eval \(ert-run-tests-batch-and-exit\)
Running 46 tests (2023-11-18 12:31:22+0500, selector ‘t’)
   passed   1/46  assess--test-indent-in-mode (0.000731 sec)
   passed   2/46  assess--test-indentation= (0.012215 sec)
   passed   3/46  assess-call-return-value (0.000235 sec)
   passed   4/46  assess-call-test-capture-fail (0.000368 sec)
   passed   5/46  assess-call-test-hook-fail (0.000153 sec)
   passed   6/46  assess-call-test-hook-test (0.000262 sec)
   passed   7/46  assess-discover-test (0.000105 sec)
   passed   8/46  assess-discover-test-has-this-been-defined (0.000141 sec)
   failed   9/46  assess-fail-for-sure (0.000157 sec)
Test assess-robot-test-execute-kmacro backtrace:
  signal(wrong-type-argument (integer-or-marker-p [104 101 108 108 111
  apply(signal (wrong-type-argument (integer-or-marker-p [104 101 108 
  (setq value-465 (apply fn-463 args-464))
  (unwind-protect (setq value-465 (apply fn-463 args-464)) (setq form-
  (if (unwind-protect (setq value-465 (apply fn-463 args-464)) (setq f
  (let (form-description-467) (if (unwind-protect (setq value-465 (app
  (let ((value-465 'ert-form-evaluation-aborted-466)) (let (form-descr
  (let* ((fn-463 #'assess=) (args-464 (condition-case err (let ((signa
  (closure (t) nil (let* ((fn-463 #'assess=) (args-464 (condition-case
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name assess-robot-test-execute-kmacro :doc
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests ... :test-map
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test assess-robot-test-execute-kmacro condition:
    (wrong-type-argument integer-or-marker-p
			 [104 101 108 108 111])
   FAILED  10/46  assess-robot-test-execute-kmacro (0.035971 sec) at test/assess-robot-test.el:65
   passed  11/46  assess-robot-test-with-switched-buffer (0.000206 sec)
   passed  12/46  assess-robot-test-with-switched-buffer-string (0.000135 sec)
   passed  13/46  assess-robot-test-with-temp-switched-buffer (0.000144 sec)
   passed  14/46  assess-test-create-multiple-directories-and-files (0.001278 sec)
   passed  15/46  assess-test-create-multiple-files (0.001157 sec)
   passed  16/46  assess-test-create-nested-directories (0.001029 sec)
   passed  17/46  assess-test-create-non-empty-file (0.000929 sec)
   passed  18/46  assess-test-create-non-empty-nested-file (0.001044 sec)
   passed  19/46  assess-test-face-at-multiple-faces (0.016726 sec)
   passed  20/46  assess-test-face-at-multiple-positions (0.001446 sec)
   passed  21/46  assess-test-face-at-simple (0.001117 sec)
   passed  22/46  assess-test-face-at-with-m-buffer (0.001136 sec)
   passed  23/46  assess-test-face-at-with-strings (0.002249 sec)
   passed  24/46  assess-test-file-face-at (0.009522 sec)
   passed  25/46  assess-test-file-roundtrip-indentation-explain= (0.017019 sec)
   passed  26/46  assess-test-file-roundtrip-indentation= (0.023087 sec)
   passed  27/46  assess-test-nest-files-recursively (0.005168 sec)
   passed  28/46  assess-test-related-file (0.000925 sec)
   passed  29/46  assess-test-roundtrip-indentation-explain= (0.004828 sec)
   passed  30/46  assess-test-roundtrip-indentation= (0.005502 sec)
   passed  31/46  assess-test-with-find-file (0.011659 sec)
   passed  32/46  buffer-string= (0.007355 sec)
   passed  33/46  buffer= (0.009311 sec)
   passed  34/46  call-capture (0.000223 sec)
   passed  35/46  call-capture-deep (0.000181 sec)
   passed  36/46  call-capture-twice (0.000170 sec)
   passed  37/46  ensure-string (0.000428 sec)
   passed  38/46  explanation-extraction (0.003972 sec)
   passed  39/46  explanation-extraction-from-result (0.003731 sec)
   passed  40/46  file-string= (0.009533 sec)
   passed  41/46  issue-4-has-type-face (0.156057 sec)
   passed  42/46  issue-5-test-example (0.004046 sec)
   passed  43/46  plist-extraction (0.000322 sec)
   passed  44/46  preserved-buffer-list (0.000203 sec)
   passed  45/46  strings-with-unequal-properties (0.000521 sec)
   passed  46/46  with-temp-buffers (0.000453 sec)

Ran 46 tests, 45 results as expected, 1 unexpected (2023-11-18 12:31:22+0500, 0.654014 sec)
1 expected failures

1 unexpected results:
   FAILED  assess-robot-test-execute-kmacro
```

**Comment by phillord** [comment]
Yes, I am getting that here also and, indeed, introduced in Emacs 29, as it runs fine in Emacs 28. Curious.

**Comment by monnier** [comment]
> Yes, I am getting that here also and, indeed, introduced in Emacs 29, as it
> runs fine in Emacs 28. Curious.

The code looks odd:

    (defun assess-robot-execute-kmacro (macro)
      "Execute the MACRO.
    
    In this case, MACRO is the \"long form\" accepted by
    `edit-kdb-macro'."
      (let ((macro (read-kbd-macro macro)))
        ;; I wanted to add a nice way to edit the macro, but sadly
        ;; edit-kdb-macro provides no nice entry point. So, we take the nasty step
        ;; of setting the last-kbd-macro instead.
        (setq last-kbd-macro macro)
        (execute-kbd-macro
         (read-kbd-macro macro))))

We pass `macro` through `read-kbd-macro` twice?
Is that intended?  Can it ever make sense?
I suspect the patch below is in order.


        Stefan


diff --git a/assess-robot.el b/assess-robot.el
index 8bb14f86c5..0d335caf26 100644
--- a/assess-robot.el
+++ b/assess-robot.el
@@ -10,7 +10,7 @@
 
 ;; The contents of this file are subject to the GPL License, Version 3.0.
 
-;; Copyright (C) 2016-2022  Free Software Foundation, Inc.
+;; Copyright (C) 2016-2023  Free Software Foundation, Inc.
 
 ;; This program is free software: you can redistribute it and/or modify
 ;; it under the terms of the GNU General Public License as published by
@@ -81,8 +81,7 @@ In this case, MACRO is the \"long form\" accepted by
     ;; edit-kdb-macro provides no nice entry point. So, we take the nasty step
     ;; of setting the last-kbd-macro instead.
     (setq last-kbd-macro macro)
-    (execute-kbd-macro
-     (read-kbd-macro macro))))
+    (execute-kbd-macro macro)))
 
 (defun assess-robot-copy-and-finish ()
   "Copy the macro in edmacro to the `kill-ring'."

**Comment by phillord** [comment]
Yeah, I noticed that. Just looks like me being overly clever in reusing variable names. I would guess I added the let binding to avoid reading the macro twice, then forgot to actually do it. Why it worked in versions of Emacs <29 I don't know.

While I am commenting, what was the reason for this change:

* dev-resources/elisp-unindented.eld:
* dev-resources/elisp-indented.eld: Change extension from `.el`.

I ask because it breaks the tests for all emacs < 29; as the `auto-mode-alist` binding for eld is new to Emacs-29. Was it to stop some scripts from adding copyright statements as has happened to `elisp-fontified.el`. Is there are a better way of suppressing this, because something similar has broken the tests in another package of mine (lentic).

**Comment by monnier** [comment]
> While I am commenting, what was the reason for this change:
> * dev-resources/elisp-unindented.eld:
> * dev-resources/elisp-indented.eld: Change extension from `.el`.

Because it doesn't contain ELisp code :-)

> I ask because it breaks the tests for all emacs < 29; as the
> `auto-mode-alist` binding for eld is new to Emacs-29.  Was it to stop
> some scripts from adding copyright statements as has happened to
> `elisp-fontified.el`.

There's a range of problems, such as cases where we tried to compile the
file, cases where we enabled `flymake-mode`, ...

> Is there are a better way of suppressing this, because
> something similar has broken the tests in another package of mine (lentic).

Better than what?

You can probably fix most of the problems with something like

    (let ((auto-mode-alist
           (cons (cons "\\.eld\\'"
                       (if (fboundp 'lisp-data-mode)
                           #'lisp-data-mode
                         #'emacs-lisp-mode)))))
      ...)

around the test.


        Stefan

**Comment by phillord** [comment]
The problem is that I am testing a function that roundtrips indentation for a file. I also do have a function that re-indents a string and the mode is explicitly specified. Testing on a file does the same thing but implicitly uses the background environment of Emacs to determine the major mode; changing the file extension breaks that because Emacs determines a different mode. In the case of ".eld", Emacs didn't bind that to lisp-data-mode in the past, so the tests break in the past.

Lentic has the same issue -- I use files which are valid Emacs lisp files in this case, but are not intended to be evaluated at any point.

Of course, I am aware that tests which are dependent on the environment are a little bit dangerous, but it's the only way I have come up with of doing what are effectively full functional tests rather than smaller scale unit style testing.

Anyway, now I am clear on the reason, I will think on the solution! Let binding `auto-mode-alist` would be the most straightforward indeed.

**Comment by phillord** [comment]
That was a little harder to fix that I expected, but both the original bug, and the errors against Emacs<29 have now been fixed.
