### ISSUE TITLE
Consider name change

### ISSUE THREAD

**Issue by phillord** [phillord/assess#3]
I'd like to consider again the issue of the name change. Sisyphus is very clever and all, but a pain to spell. @jwiegley suggests "check". @syohex as the only other contributor any suggestions welcome.

@jwiegley, btw, have you considered changing your name because I keep spelling it wrong as well:-)

**Comment by Wilfred** [comment]
This can be closed now, no?

**Comment by phillord** [comment]
Yes, that's true!

**Comment by Fuco1** [comment]
As a non-native english speaker, the current name pops up very different connotations than what it actually is.  I was utterly confused when people started talking to me about this project.

I suppose it's too late now though :(

**Comment by phillord** [comment]
Probably, yes!

Are you reading it as "ass-ess" -- i.e. lots of donkeys? I hadn't thought of that.

**Comment by Fuco1** [comment]
Yea, as a plural, which is just on `-es` but when you read/pronounce it it ends up the same in your head (of course, not when you have proper accent...).  Language is funny.

**Comment by jwiegley** [comment]
I still like "check". :)  Changing my own name, maybe a touch harder.

**Comment by phillord** [comment]
Neither check nor assess fit entirely now, as it has expanded beyond it's original scope. Should have given it a semantics free name, like "John" 

```
(john= "hello" "goodbye")
```

Maybe not.

**Comment by Fuco1** [comment]
`john` definitely has the semantic value of "bloody awesome"... that wouldn't make sense!
