### ISSUE TITLE
Using assess-face-at= to verify that things aren't highlighted

### ISSUE THREAD

**Issue by Wilfred** [phillord/assess#4]
Maybe I'm being dumb, but I can't see any way of verifying that faces aren't applied.

If I assert that unfontified text has a font, the assertion message says that the face is nil:

``` lisp
(ert-deftest has-type-face ()
  (should
   (assess-face-at= "foo bar" 'fundamental-mode
                    "bar" 'font-lock-type-face)))
```

This fails, as expected, with:

```
    (ert-test-failed
     ((should
       (assess-face-at= "foo bar" 'fundamental-mode "bar" 'font-lock-type-face))
      :form
      (assess-face-at= "foo bar" fundamental-mode "bar" font-lock-type-face)
      :value nil :explanation "Face does not match expected value
    Expected: font-lock-type-face
    Actual: nil
    Location: 5
    Line Context: foo bar
    bol Position: 1
"))
```

However, if I need to use nil to assert that no faces are applied, I would expect nil here:

``` lisp
ELISP> (assess-face-at= "def" 'python-mode "def" nil)
t
```

I can work around this by using `(assess-face-at= "def" 'python-mode "def" '(nil))`, but I think it's a bug.

**Comment by phillord** [comment]
Yeah, nil punning was not working for me at all there.

Thanks for the catch!

**Comment by Wilfred** [comment]
Thank you :)
