### ISSUE TITLE
Documentation is broken?

### ISSUE THREAD

**Issue by Fuco1** [phillord/assess#8]
Hi.

This seems like a rad project but I have no idea how to use it or even what is available.  The org file with the documentation is rather empty and the readme doesn't have any example either.

Would you consider writing something up?

**Comment by DamienCassou** [comment]
I think this documentation is nice: http://www.russet.org.uk/blog/3140 (and the page that is linked from this one).

**Comment by phillord** [comment]
@Fuco1 There always was documentation, but in classic academic fashion it has been in a way which is terrible clever, but not terribly useful.

I have an excuse in this case.  I wrote assess _because_ of the clever documentation system, so it seems natural to use it. I've generated the doc for you, and added more to the readme describing how to view it.

I'll add the rest later (famous last words -- please nag if I don't).

**Comment by Fuco1** [comment]
Nice, thanks :) The link is enough and the documentation there seems usable.  I was simply unaware of its existence.

**Comment by phillord** [comment]
If you have time to give lentic-server a go, I'd be grateful. Be nice to know if it works for anyone other than me!

**Comment by DamienCassou** [comment]
@phillord I don't know what lentic-server is, but I successfully used lentic to create PR https://github.com/phillord/assess/pull/7.

**Comment by phillord** [comment]
@DamienCassou https://github.com/phillord/lentic-server

It's a front end for packages documented with lentic. It compiles lentic source to org-mode, then to HTML, then serves then to the web.
